SELECT 
        SYSDATE AS NOW,
        SYSDATE-1 AS YESTERDAY,
        SYSDATE+1 AS TOMORROW
FROM DUAL;

SELECT
        SYSDATE,
        ADD_MONTHS(SYSDATE, 3)
FROM DUAL;

SELECT
        EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 120) AS WORK10YEAR
FROM EMP;

SELECT EMPNO, ENAME, HIREDATE, SYSDATE
FROM EMP
WHERE ADD_MONTHS(HIREDATE, 480) > SYSDATE;

SELECT 
        EMPNO, ENAME, HIREDATE, SYSDATE, 
        MONTHS_BETWEEN(HIREDATE, SYSDATE) AS MONTHS1, 
        MONTHS_BETWEEN(SYSDATE, HIREDATE) AS MONTHS2, 
        TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) AS MONTHS3
FROM EMP;

SELECT SYSDATE,
        NEXT_DAY(SYSDATE, '¿ù¿äÀÏ'),
        LAST_DAY(SYSDATE)
FROM DUAL;

SELECT SYSDATE,
        ROUND(SYSDATE, 'CC') AS FORMAT_CC,
        ROUND(SYSDATE, 'YYYY') AS FORMAT_YYYY,
        ROUND(SYSDATE, 'Q') AS FORMAT_Q,
        ROUND(SYSDATE, 'DDD') AS FORMAT_DDD,
        ROUND(SYSDATE, 'HH') AS FORMAT_HH
FROM DUAL;