-- 9-4
SELECT *
FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
                        FROM EMP
                        GROUP BY DEPTNO);
                        
-- 9-5
SELECT E10.EMPNO, E10.ENAME, D.DEPTNO, D.DNAME, D.LOC
FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10, (SELECT * FROM DEPT) D
WHERE E10.DEPTNO = D.DEPTNO;  

WITH
E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10),
D AS (SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, D.DEPTNO, D.DNAME, D.LOC
FROM E10, D
WHERE E10.DEPTNO = D.DEPTNO;

SELECT *
FROM EMP E1
WHERE SAL > (SELECT MIN(SAL)
                FROM EMP E2
                WHERE E2.DEPTNO = E1.DEPTNO)
ORDER BY DEPTNO, SAL;

SELECT MIN(E2.SAL)
FROM EMP E1, EMP E2
WHERE E2.DEPTNO = E1.DEPTNO;

-- 9-6
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL,
        (SELECT GRADE
        FROM SALGRADE
        WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
        DEPTNO,
        (SELECT DNAME
        FROM DEPT
        WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME
FROM EMP E;

-- 연습 문제
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.JOB = (SELECT JOB
                FROM EMP
                WHERE UPPER(ENAME) = UPPER('allen'))
ORDER BY E.SAL DESC;

SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE
FROM 
        EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
        JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE E.SAL > (SELECT AVG(SAL)
                FROM EMP)
ORDER BY E.SAL DESC, E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE E.DEPTNO = 10
AND E.JOB NOT IN (SELECT JOB
                FROM EMP
                WHERE DEPTNO = 30);
                
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE E.SAL > (SELECT MAX(SAL)
                FROM EMP
                WHERE UPPER(JOB) = UPPER('SALESMAN'))
ORDER BY E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE E.SAL > ALL (SELECT SAL
                FROM EMP
                WHERE UPPER(JOB) = UPPER('SALESMAN'))
ORDER BY E.EMPNO;