SELECT E.JOB, E.EMPNO,E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND JOB = (SELECT JOB
                FROM EMP
                WHERE UPPER(ENAME) = UPPER('allen'));
                
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE
FROM DEPT D JOIN EMP E ON (D.DEPTNO = E.DEPTNO) 
JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE SAL > (SELECT AVG(SAL)
                FROM EMP)
ORDER BY E.SAL DESC, E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, D.DEPTNO, D.LOC
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE E.DEPTNO = 10
AND JOB NOT IN (SELECT JOB
                FROM EMP
                WHERE DEPTNO = 30);

SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE SAL > (SELECT MAX(SAL)
                FROM EMP
                WHERE UPPER(JOB) = UPPER('SALESMAN'))
ORDER BY E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE SAL > ALL (SELECT SAL
                FROM EMP
                WHERE UPPER(JOB) = UPPER('SALESMAN'))
ORDER BY E.EMPNO;